# Here is the config for the file groups
# Modify it as you wish to change how files are sorted
# For example, you may want to move .csv from the spreadsheet
# category to the data category.

Audio:
  - aif
  - cda
  - mid
  - midi
  - mp3
  - mpa
  - ogg
  - wav
  - wma
  - wpl

Compactados:
  - 7z
  - arj
  - deb
  - pkg
  - rar
  - rpm
  - tar.gz
  - z
  - zip

system_images:
  - bin
  - dmg
  - iso
  - toast
  - vcd

Dados:
  - dat
  - db
  - dbf
  - log
  - mdb
  - sav
  - sql
  - tar
  - xml

Executaveis:
  - apk
  - bat
  - bin
  - cgi
  - pl
  - com
  - exe
  - gadget
  - jar
  - py
  - wsf

Fontes:
  - fnt
  - fon
  - otf
  - ttf

Imagens:
  - ai
  - bmp
  - gif
  - ico
  - jpeg
  - jpg
  - png
  - ps
  - psd
  - svg
  - tif
  - tiff

web_files:
  - asp
  - aspx
  - cer
  - cfm
  - css
  - htm
  - html
  - js
  - jsp
  - part
  - php
  - rss
  - xhtml

Apresentacoes:
  - key
  - odp
  - pps
  - ppt
  - pptx

programming:
  - c
  - class
  - cpp
  - cs
  - h
  - java
  - swift

Planilhas:
  - ods
  - xlr
  - xls
  - xlsx
  - csv

system_files:
  - bak
  - cab
  - cfg
  - cpl
  - cur
  - dll
  - dmp
  - drv
  - icns
  - ico
  - ini
  - ink
  - msi
  - sys
  - tmp

Videos:
  - 3g2
  - 3gp
  - avi
  - flv
  - h264
  - m4v
  - mkv
  - mov
  - mp4
  - mpg
  - mpeg
  - rm
  - swf
  - vob
  - wmv

Documentos:
  - doc
  - docx
  - odt
  - pdf
  - rtf
  - tex
  - txt
  - wks
  - wps
  - wpd

Atalhos:
  - url
